export const TOGGLE_THEME = "toggle-theme"
export const TOGGLE_PANEL_DISPLAY = "toggle-panel-display"
export const SET_GRADIENT_STYLE = "set-gradient-style"
export const SET_LINEAR_DIRECTION = "set-linear-direction"
export const SET_RADIAL_POSITION = "set-radial-position"
export const SET_RADIAL_SHAPE = "set-radial-shape"
export const SET_CONIC_START_ANGLE = "set-conic-start-angle"